server:
  port: 80

#spring:
#  security:
#    user:
#      name: admin
#      password: admin

spring:
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/gyg_user?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath://com/gyg/user/mapper/xml/**.xml
